### ISSUE TITLE
anotaçõens

### ISSUE THREAD

**Issue by rodft2** [Grupo-77/processos-dev#1]
# Relato de Problema  
Anotações não deletam

## Descrição  
As anotações nas tarefas dos escoteiros não são deletadas.

## Passos para Reproduzir

1. Vá a "Contactos" e acesse "Progresso".
2. Edite um escoteiro.
3. Assine uma prova.
4. Escreva algo na anotação.
5. Saia da edição.
6. Volte para a edição.
7. Delete a anotação.
8. Saia da edição.
9. Volte para a edição.  
   A anotação ainda está lá.

## Resultado Esperado  
Que a anotação não estivesse mais lá.

## Resultado Obtido  
A anotação ainda estava presente.

## Informações Adicionais

- **Tipo de Aplicação**: [Selecione a aplicação onde o problema ocorreu]  
  - [x] Progresso (Web)

- **Método de Autenticação**:  
  - [x] Google

- **Ambiente**:
  - **Sistema Operativo**: Windows
  - **Versão do Browser**: Chrome
  - **Data da Ocorrência**: 21/08/2024

- **Capturas de ecrã e/ou detalhes**:  
  [Anexe capturas de ecrã e outros detalhes importantes acerca do erro.]

## Checklist

- [x] Confirmo que estava a usar a versão mais recente da aplicação.
- [x] Confirmo que não incluí dados pessoais ou credenciais neste relatório.

---

**Comment by PedroCavalheiro** [comment]
Não foi possível reproduzir o erro.
