### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DIOGO62743** [Grupo-77/processos-dev#10]
# Relato de Problema

## Descrição

Fui tentar fazer login na plataforma, mas não consegui com o meu email e palavra-passe.

Passos para Reproduzir
Aceda à página de login.
Introduza o email e a palavra-passe.
Clique no botão "Entrar".
Verifique a mensagem de erro apresentada.

Resultado Esperado
Esperava conseguir aceder à plataforma utilizando o meu email e palavra-passe, sem qualquer erro ou bloqueio, sendo redirecionado para a página inicial após a autenticação.

Resultado Obtido
Não consegui aceder à plataforma com o meu email e palavra-passe. Após tentar fazer login, apareceu uma mensagem de erro e permaneci na página de autenticação, sem acesso ao conteúdo da plataforma.

## Informações Adicionais

- **Tipo de Aplicação**: [Selecione a aplicação onde o problema ocorreu]
  - [x ] Progresso (Web)
  - [ ] Progresso (Android)
  - [ ] Processos (Web)

- **Método de Autenticação**:
  - [ ] Google
  - [ x] Email e Senha
  - [ ] QR Code / Link

-Ambiente:

Sistema Operativo: [por exemplo, Windows 10]
Versão do Browser: [por exemplo, Opera GX]
Data da ocorrência: [por exemplo, 24/10/2024]
Dispositivo (para PC): [por exemplo, Lenovo etc.]
Capturas de ecrã e/ou detalhes: [Anexe capturas de ecrã e outros detalhes importantes acerca do erro.]
- **Capturas de ecrã e/ou detalhes**:
  
![ok](https://github.com/user-attachments/assets/9109ffc9-e002-4755-a5a8-3f5a59068091)
](url)
## Comentários Adicionais

[Qualquer outra informação que possa ser útil para resolver o problema.]

## Checklist

 - [x ] Confirmo que estava a usar a versão mais recente da aplicação;
 - [ x] Confirmo que não incluí dados pessoais ou credenciais no presente relatório.

**Comment by PedroCavalheiro** [comment]
Esquecer-se da palavra passe não é um erro de sistema. Foi enviado um link de reset de password.

**Comment by PedroCavalheiro** [comment]
Esquecer-se da palavra passe não é um erro de sistema. Foi enviado um link de reset de password.

**Comment by PedroCavalheiro** [comment]
-
