### ISSUE TITLE
pesquisa por nome 

### ISSUE THREAD

**Issue by rodft2** [Grupo-77/processos-dev#3]
# Pedido de Funcionalidade: Pesquisa por Nome

## Descrição
Adicionar uma funcionalidade de pesquisa que permita encontrar elementos em processos pelo nome e número associativo. Isso facilitará a localização rápida de informações específicas.

## Justificação
Em grupos maiores, pode haver muitos elementos, o que torna a navegação manual ineficiente. Apesar da existência de categorias, uma pesquisa direta por nome ou número associativo é mais eficiente quando o usuário já sabe o que está procurando.

## Implementação Sugerida
Incluir uma barra de pesquisa que permita a entrada de nomes ou números associativos, retornando resultados relevantes.

## Impacto
A implementação dessa funcionalidade aumentará a eficiência na localização de elementos específicos, economizando tempo e esforço ao usuário, que não precisará percorrer várias linhas para encontrar a informação desejada.

## Alternativas Consideradas
Embora as categorias existentes sejam úteis, elas não são suficientes para necessidades de pesquisa direta.

## Informações Adicionais
![image](https://github.com/user-attachments/assets/b0eb2dff-f717-4f4a-a9a7-c660aca00e57)

**Comment by PedroCavalheiro** [comment]
O caso de uso assumido para a vista de detalhe é para uma vista geral, e não de utilizadores específicos (para isso serve a vista geral). Nesse sentido, não é necessária a intervenção nesta página.
