### ISSUE TITLE
anexar imagens junto com os produtos

### ISSUE THREAD

**Issue by rodft2** [Grupo-77/processos-dev#4]
# Pedido de Funcionalidade: Anexar Imagens aos Produtos

## Descrição
Adicionar a capacidade de anexar imagens junto aos produtos. Isso permitirá uma identificação visual dos produtos, facilitando a procura e reconhecimento, mesmo que os nomes não sejam conhecidos.

## Justificação
É mais fácil identificar e procurar produtos através de imagens do que apenas pelos nomes, especialmente para usuários que não estão familiarizados com a nomenclatura utilizada. Essa funcionalidade também beneficia novos usuários, que podem ter dificuldade em associar nomes a itens específicos.

## Implementação Sugerida
Incluir um campo ou área de anexo para adicionar imagens aos produtos no sistema, de modo que cada produto possa ter uma imagem associada.

## Impacto
Essa funcionalidade facilitará a busca e a compreensão dos produtos, ajudando os usuários a identificar rapidamente os itens, melhorando a usabilidade do sistema.

## Alternativas Consideradas
Nenhuma alternativa foi considerada.

## Informações Adicionais
![image](https://github.com/user-attachments/assets/13a2e6d3-8dd3-4441-8d6c-961afbe58a44)
![image](https://github.com/user-attachments/assets/edf5409b-399e-4d78-a988-edbadb5b0d5c)

**Comment by PedroCavalheiro** [comment]
Feito e em produção
